### ISSUE TITLE
macOS使用appstore publisher时，报provision profile无效的错误

### ISSUE THREAD

**Issue by yohom** [fastforgedev/fastforge#126]
直接使用`flutter build macos`然后在xcode中archive可以上传到appstoreconnect，但是用[flutter_distributor](https://github.com/leanflutter/flutter_distributor)不行。
配置脚本：
```yaml
  # macOS appstore
  - name: macstore
    jobs:
      - name: release-prod-macos
        package:
          platform: macos
          target: zip
          build_args:
            verbose:
            release: true
            dart-define:
              APP_ENV: prod
              SANDBOX: true
        publish_to: appstore
```
错误信息：
```
NSUnderlyingError = "Error Domain=IrisAPI Code=-19241 \"Asset validation failed\" UserInfo={status=409, detail=Invalid Provisioning Profile. The provisioning profile included in the bundle *** is invalid. [Invalid 'com.apple.developer.aps-environment' entitlement value.] For more information, visit the macOS Developer Portal., id=58a2ee5a-fcc3-4d5f-94f6-d482f09a8c9d, code=STATE_ERROR.VALIDATION_ERROR.90283, title=Asset validation failed, NSLocalizedFailureReason=Invalid Provisioning Profile. The provisioning profile included in the bundle *** is invalid. [Invalid 'com.apple.developer.aps-environment' entitlement value.] For more information, visit the macOS Developer Portal., NSLocalizedDescription=Asset validation failed}";
    "iris-code" = "STATE_ERROR.VALIDATION_ERROR.90283";
}
```
