### ISSUE TITLE
MakeError: type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by Fenekhu** [fastforgedev/fastforge#259]
While trying to build a linux AppImage, I get the following error:

```
MakeError: type 'Null' is not a subtype of type 'String' in type cast
#0      AppPackageMakerAppImage._make (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:296:7)
<asynchronous suspension>
#1      UnifiedDistributor.package (package:unified_distributor/src/unified_distributor.dart:197:35)
<asynchronous suspension>
...
```

It seems like I'm missing something, but I can't tell what based on the line that it gave me. (Side note, capturing every unexpected error and just taking the string feels very strange to me for this exact reason, that now I have no idea how to tell where exactly anything went wrong).

Here is the job in the `distribute_options.yaml` that creates it:

```yaml
- name: linux-appimage
  package:
    platform: linux
    target: appimage
```

Here is the `make_config.yaml`: (the actual app name has been replaced with "My App", etc)

```yaml
display_name: My App

icon: assets/images/icon.png

keywords:
  - Music
  - Player

generic_name: My App

actions: []

categories:
  - Music

startup-notify: true

# im not sure what difference manually specifying this makes.
include:
  - libmpv.so.2

metainfo: linux/packaging/com.fenekhu.my_app.appdata.xml
```
