### ISSUE TITLE
不能在指定执行的文件， 例如 lib/main.dev.dart.   lib/main.stg.dart.  lib/main.prod.dart 等

### ISSUE THREAD

**Issue by jackson0122** [fastforgedev/fastforge#268]

**Comment by lijy91** [comment]
可以通过 build_args 来指定 target
```yaml
variables:
  PGYER_API_KEY: 'your api key'
output: dist/
releases:
  - name: dev
    jobs:
      - name: dev-android
        package:
          platform: android
          target: apk
          build_args:
            target: main.dev.dart
      - name: stag-android
        package:
          platform: android
          target: apk
          build_args:
            target: main.stg.dart
```
