### ISSUE TITLE
是否支持flutter打包的扩展参数

### ISSUE THREAD

**Issue by gstory0404** [fastforgedev/fastforge#277]
比如开启混淆
```
flutter build apk --release --obfuscate --split-debug-info=out/android
```

**Comment by lijy91** [comment]
支持的，添加到 build_args 中即可，但需要转换为 yaml 的格式，如 `--obfuscate` 就是 `obfuscate: true`
```
releases:
  - name: dev
    jobs:
      # Build and publish your apk pkg to pgyer
      - name: release-dev-android
        package:
          platform: android
          target: apk
          build_args:
            obfuscate: true
            split-debug-info: out/android
```
